name: Build and test projects

on:
  push:
    branches:
      - '*'
      - '!release'
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Configure dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'ga'
    - name: Configure nuget feed
      run: dotnet nuget add source "https://nuget.pkg.github.com/CodicePlastico/index.json" --store-password-in-clear-text -u mrs-developer -p ${{ secrets.REGISTRY_TOKEN }} -n github 
    - name: Build
      run: |
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build
    